services:
  nats:
    container_name: nats
    restart: always
    image: nats:latest
    ports:
      - ${NATS_PORT}:${NATS_PORT}
      - ${NATS_INTER_PORT}:${NATS_INTER_PORT}
    networks:
      - microservice-network
      - database-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
    networks:
      - microservice-network

  postgres:
    container_name: postgres
    restart: always
    image: postgres:13.18
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - /tmp/data/postgres:/data/postgres
    networks:
      - microservice-network
      - database-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api-gateway:
    container_name: api-gateway
    ports:
      - ${PORT}:${PORT}
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    image: api-gateway:latest
    networks:
      - microservice-network
      - database-network
    environment:
      NATS_URL: ${NATS_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SALT_ROUNDS: ${SALT_ROUNDS}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - nats
      - postgres
      - redis

  account:
    container_name: account
    build:
      context: .
      dockerfile: ./apps/account/Dockerfile
    image: account:latest
    networks:
      - microservice-network
      - database-network
    environment:
      NATS_URL: ${NATS_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SALT_ROUNDS: ${SALT_ROUNDS}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_AUTHORIZE_URL: ${GITHUB_AUTHORIZE_URL}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    depends_on:
      - nats
      - postgres
      - redis

networks:
  database-network: {}
  microservice-network: {}

volumes:
  redis-data:
