services:
  postgres:
    image: postgres:13.18
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-test
      POSTGRES_HOST_AUTH_METHOD: trust

  node-todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-todo-app
    restart: always
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todo-test
      NODE_ENV: production
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge 