export const FILE_UPLOADER_TOKEN = 'FILE_UPLOADER_TOKEN';
export const FILE_UPLOADER_MODULE_TOKEN = 'FILE_UPLOADER_MODULE_TOKEN';
export const FILE_UPLOADER_OPTIONS_TOKEN = 'FILE_UPLOADER_OPTIONS_TOKEN';
